app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from app.views import common, sales

urlpatterns = [
    path('', sales.index, name="index"),
    path('sales', sales.sales, name="sales"),
    path("login", common.login_view, name="login"),
    path("logout", common.logout_view, name="logout"),
    path("register", common.register, name="register"),
    path('order', sales.order_view, name="order"),
    path('orders', sales.orders, name="orders"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bpinventory/urls.py
from django.contrib import admin
from django.urls import path, include
from app.urls import urlpatterns as app_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(app_urls)),
]

app/models.py
import uuid

from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.db import models, connection


class MyManager(models.Manager):
    def raw_as_qs(self, raw_query, params=()):
        """Execute a raw query and return a QuerySet.  The first column in the
        result set must be the id field for the model.
        :type raw_query: str | unicode
        :type params: tuple[T] | dict[str | unicode, T]
        :rtype: django.db.models.query.QuerySet
        """
        cursor = connection.cursor()
        try:
            cursor.execute(raw_query, params)
            return self.filter(id__in=(x[0] for x in cursor))
        finally:
            cursor.close()

class ClientManager(models.Model):
    email = models.CharField(max_length=30, primary_key=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

class UserAccount(AbstractUser):
    manager = models.ForeignKey(ClientManager, on_delete=models.DO_NOTHING, default='admin@admin.ru')

class BasicModels(models.Model):
    modified_date = models.DateTimeField(auto_now=True, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class AccountManager(BaseUserManager):
    def create_user(self, username, password=None, **kwargs):
        if not username:
            raise ValueError("Users must have a valid username!")

        account = self.model(
            username=username,
            firstname=kwargs.get('firstname', None),
            middle_initial=kwargs.get('middle_initial', None),
            lastname=kwargs.get('lastname', None),
            gender=kwargs.get('gender', None),
            position=kwargs.get('position', None),
            is_staff=kwargs.get('is_staff', True),
        )
        account.set_password(password)
        account.save()

        return account

    def create_superuser(self, username, password=None, **kwargs):
        account = self.create_user(username, password, **kwargs)
        account.is_admin = True
        account.save()
        return account


# class UserAccount(AbstractBaseUser):
#     username = models.CharField(unique=True, max_length=50)
#
#     is_staff = models.BooleanField(default=False)
#     is_admin = models.BooleanField(default=False)
#     can_encode = models.BooleanField(default=False)
#
#     firstname = models.CharField(max_length=200, blank=True, null=True)
#     middle_initial = models.CharField(max_length=2, blank=True, null=True)
#     lastname = models.CharField(max_length=200, blank=True, null=True)
#     gender = models.CharField(max_length=1, blank=True, null=True)
#     position = models.CharField(max_length=200, blank=True, null=True)
#
#     objects = AccountManager()
#
#     USERNAME_FIELD = 'username'
#     REQUIRED_FIELDS = ['firstname', 'lastname']
#
#     def get_full_name(self):
#         return f"{self.firstname} {self.lastname}"
#
#     def get_short_name(self):
#         return self.username
#
#     @property
#     def is_superuser(self):
#         return self.is_admin
#
#     def has_perm(self, perm, obj=None):
#         return self.is_admin
#
#     def has_module_perms(self, app_label):
#         return self.is_admin
#
#     def __unicode__(self):
#         return self.username

class UserPainInformation(models.Model):
    id = models.OneToOneField(UserAccount, on_delete=models.DO_NOTHING, primary_key=True)
    inn = models.CharField(max_length=12, unique=True)
    kpp = models.CharField(max_length=9, null=True)
    ogrn = models.CharField(max_length=15, null=True)
    okpo = models.CharField(max_length=10, null=True)
    oktmo = models.CharField(max_length=11, null=True)
    legal_address = models.CharField(max_length=255, null=True)
    full_name = models.CharField(max_length=255, null=True)
    director = models.CharField(max_length=255, null=True)
    state_status = models.CharField(max_length=10, null=True)
    type = models.CharField(max_length=10, default='INDIVIDUAL')


class Category(BasicModels):
    name = models.CharField(max_length=100, null=True, blank=True, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'categories'
        verbose_name = 'Category'
        verbose_name_plural = "Categories"


class Item(BasicModels):
    objects = MyManager()
    name = models.CharField(max_length=100, null=True, blank=True, unique=True)
    selling_price = models.DecimalField(null=True, blank=True, decimal_places=3, max_digits=15)
    original_price = models.DecimalField(null=True, blank=True, decimal_places=3, max_digits=15)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    stock = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'items'
        verbose_name = 'Item'
        verbose_name_plural = "Items"
        ordering = ['name']


class Supplier(BasicModels):
    name = models.CharField(max_length=100, null=True, blank=True, unique=True)
    address = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'suppliers'
        verbose_name = 'Supplier'
        verbose_name_plural = "Suppliers"


class StatusTransfer(models.Model):
    id = models.CharField(max_length=1, primary_key=True)
    description = models.CharField(max_length=255)


class Transfer(BasicModels):
    #To = models.ForeignKey(Supplier, related_name="to+", on_delete=models.DO_NOTHING)
    items = models.ManyToManyField(Item, through="ItemTransfer")
    user = models.ForeignKey(UserAccount, on_delete=models.DO_NOTHING)
    status = models.ForeignKey(StatusTransfer, on_delete=models.DO_NOTHING, default='n')
    #delivered_by = models.CharField(max_length=255, default='')



class ItemTransfer(BasicModels):
    quantity = models.IntegerField(default=1)
    total = models.FloatField(default=1000)
    item = models.ForeignKey(Item, on_delete=models.DO_NOTHING)
    transfer = models.ForeignKey(Transfer, null=True, blank=True, on_delete=models.DO_NOTHING)

    @property
    def calculate_total(self):
        return self.item.original_price * self.quantity


class Arrival(BasicModels):
    types = (
        ('cash', 'cash'),
        ('payable', 'payable'),
    )
    type = models.CharField(max_length=10, choices=types, default='cash')
    items = models.ManyToManyField(Item, through='ItemArrival')
    supplier = models.ForeignKey(Supplier, on_delete=models.DO_NOTHING)
    receipt_no = models.IntegerField()
    user = models.ForeignKey(UserAccount, on_delete=models.DO_NOTHING)

    def __unicode__(self):
        return self.id

    def items_list(self):
        return [a.item for a in self.items.all()]

    @staticmethod
    def apply_filter(start, end, supplier):
        items = Arrival.objects.filter(supplier=supplier).filter(created_date__gt=start, created_date__lt=end)
        return items

    @property
    def get_grand_total(self):
        grand_total = 0
        items_set = self.items.all()
        for item in items_set:
            grand_total = grand_total + item.calculate_total
        return grand_total

    class Meta:
        db_table = 'arrivals'
        verbose_name = 'Arrival'
        verbose_name_plural = "Arrivals"


class ItemArrival(BasicModels):
    item = models.ForeignKey(Item, on_delete=models.DO_NOTHING)
    arrival = models.ForeignKey(Arrival, on_delete=models.DO_NOTHING)
    quantity = models.DecimalField(null=True, blank=True, decimal_places=3, max_digits=15, default=0)
    price = models.DecimalField(null=True, blank=True, decimal_places=3, max_digits=15, default=0)

    def __unicode__(self):
        return f"{self.item.name} {self.quantity}"

    @property
    def calculate_total(self):
        return self.item.original_price * self.quantity

    class Meta:
        db_table = 'item_arrivals'
        verbose_name = 'Item Arrival'
        verbose_name_plural = "Item Arrivals"


class Permission(BasicModels):
    user = models.ForeignKey(UserAccount, on_delete=models.DO_NOTHING)
    message = models.TextField()
    requested_report = models.BooleanField(default=False)
    requested_arrival = models.BooleanField(default=False)


class Event(BasicModels):
    correlation_id = models.UUIDField(default=uuid.uuid4(), unique=True)
    event_action = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    payload = models.TextField(null=True, blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    auth_user = models.ForeignKey(UserAccount, on_delete=models.DO_NOTHING)
    status = models.SmallIntegerField(default=0)

    class Meta:
        db_table = 'events'
        verbose_name = 'Event Log'
        verbose_name_plural = "Event Logs"

app/views/sales.py
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect
from app.models import Item, Transfer, ItemTransfer, StatusTransfer
from django.urls import reverse
from .. import send_email


def index(request):
    return HttpResponseRedirect(reverse("sales"))

def sales(request):
    if request.user.is_authenticated:
        items = Item.objects.filter(is_active=True)
        ctx = {
            'title': 'Sales',
            'items': items
        }
        return render(request, "sales/index.html", ctx)
    else:
        return HttpResponseRedirect(reverse("login"))

# Создание заказа
def order_view(request):
    if request.method == "POST":
        transfer = Transfer.objects.create(user_id=request.user.id,)  # Создали заказ
        q = 0; t = 0.0; item_id = 0  # временные переменные для количества, стоимости и  айди товара
        for key in request.POST:
            if key != 'csrfmiddlewaretoken':
                if key[len(key)-5:] == 'total':
                    t = float(request.POST[key])
                else:
                    q = int(request.POST[key])
                    item_id = int(key)
                if t != 0 and q != 0:
                    #Изменим остатки на складе
                    ItemTransfer.objects.create(quantity=q, item_id=item_id,
                                                transfer_id=transfer.id, total=t)  # добавили количество и ид товаров
                    item = Item.objects.get(id=item_id)
                    item.stock = item.stock - q
                    item.save()
                    q = 0; t = 0; item_id = 0
        # Отправим письма
        # client_letter_body = "Вы оформили заказ. Номер заказа - {}. В ближайшее время мы Вам перезвоним".format(transfer.id)
        # manager_letter_body = "Клиент id {0} {2} {3} оформил новый заказ № {1}.".format(request.user.id, transfer.id,
        #                                                                                 request.user.first_name, request.user.last_name)
        # client_mail = request.user.email
        # manager_mail = request.user.manager_id
        # subject = 'Новый заказ №{}'.format(transfer.id)
        # send_email.SendMail(client_mail, subject, client_letter_body)
        # send_email.SendMail(manager_mail, subject, manager_letter_body)
        # конец рассылки писем
        return render(request, 'order.html', context={'order_id': transfer.id})
    else:
        return HttpResponseRedirect(reverse("index"))

# Переход на страницу заказов
def orders(request):
    orders = Transfer.objects.filter(user_id=request.user.id).annotate(total=Sum('itemtransfer__total'))
    ctx = {
        'title': 'Ваши заказы',
        'orders': orders,
    }
    return render(request, 'sales/orders.html', ctx)

app/templates/sales/cart-items.html
<table id="cart-table" class="table table-hover table-sm" style="width:100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Discount</th>
            <th>Total</th>
            <th>Action</th>
            <th>Stock</th>
            <th>ID</th>
        </tr>
    </thead>
</table>

app/templates/sales/get-items.html
<table id="itogo_table" class="table table-hover table-sm" style="width:100%">
    <tr>
        <td><h4>Итого:</h4></td>
        <td style="width: 475px; text-align: right; padding-right: 35px"><h4><u>0</u></h4></td>
        <td><input onclick="json_to_respone()" disabled="True" id="make_order" type="submit" class="btn btn-sm btn-primary" value="Купить"></td>
    </tr>
</table>

app/templates/sales/index.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block extra_css %}
    <style>
        span {
            cursor: pointer;
        }

        .minus, .plus {
            width: 21px;
            height: 3px;
            background: #f2f2f2;
            border-radius: 4px;
            border: 1px solid #ddd;
            display: inline-table;
            vertical-align: middle;
            text-align: center;
        }

        .sales-input {
            height: 27px;
            width: 50px;
            text-align: center;
            font-size: 15px;
            border: 1px solid #ddd;
            border-radius: 2px;
            display: inline-block;
            vertical-align: middle;
        }
        .sales-input2{
            height: 27px;
            width: 50px;
            text-align: center;
            font-size: 15px;
            border: 1px solid #ddd;
            border-radius: 2px;
            display: inline-block;
            vertical-align: middle;
        }
        .total-field{
            width: 75px;
        }

        .dataTables_filter {
           float: left !important;
        }
    </style>
{% endblock %}

{% block content %}
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="row">
        <div class="col-md-7">
            <div class="card">
                <div class="card-body">
                    {% include 'sales/items.html' %}
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <form action="{% url 'order' %}" method="post">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        {% include 'sales/cart-items.html' %}
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        {% include 'sales/get-items.html' %}
                    </div>
                </div>
            </form>
        </div>
    </div>


{% endblock %}

{% block extra_js %}
    <script>
        $(document).ready(function () {
            var itemTable = $('#data-table').DataTable({
                responsive: true,
                paging: false,
                pageLength: 20,
                searching: true,
                ordering: false,
                autoWidth: false,
                dom: '<"pull-left"f><"pull-right"l>tip',
                initComplete: function () {
                    var searchField = $('.dataTables_filter input[type="search"]');
                    searchField.css({'width': '500px', 'display': 'inline-block'});
                    searchField.addClass('mr-auto')
                }
            });
            var cartTable = $('#cart-table').DataTable({
                responsive: true,
                paging: false,
                searching: false,
                ordering: false,
                autoWidth: false,
                info: false,
                columnDefs: [
                    {
                        targets: [ 2 ],
                        render  : function(data, type, row){
                            return '<div class="number">' +
                                        '<span class="minus">-</span>' +
                                            '<input class="sales-input2" type="text"  name="' + data + '" value="1" max="' + row[6] + '"/>' +
                                        '<span class="plus">+</span>' +
                                    '</div>';
                        }
                    },
                    {
                        targets: [ 3 ],
                        render  : function(data, type, row){
                            return '<div class="sales-input2"><span></span></div>';
                                {#'<input class="sales-input2" type="number" name="' + data + '-discount" value="0" min="0"/>';#}
                        }
                    },
                    {
                        targets: [4],
                        render  : function(data, type, row){
                             return '<div class="sales-input2"><input name="'+row[7]+'_total"    type="text"'+
                             'style="width:8ch" value="'+Number(data).toFixed(3)+'" readonly>';
                        }
                    },
                    {
                        "targets": [ 6 ],
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "targets": [ 7 ],
                        "visible": false,
                        "searchable": false
                    },
                ]
            });

            $(document).on('click', '.minus', function (e) {
                var $input = $(this).parent().find('input');
                var count = parseInt($input.val()) - 1;
                count = count < 1 ? 1 : count;
                $input.val(count);
                $input.change();
                return false;
            });

             $(document).on('click', '.plus', function (e) {
                var $input = $(this).parent().find('input');
                $input.val(parseInt($input.val()) + 1);
                $input.change();
                return false;
            });
             $(document).on('change', '.sales-input2', function (e){
                 let $input_change = $(this).parent().find('input');
                 let $tds = $(this).parent().parent().parent().find('td');
                 let stock = parseInt(cartTable.row($tds).data()[6]);
                 let num = parseInt($input_change[0].value);
                 if (num > stock){
                     num = stock
                     $input_change[0].value = num
                 }
                 let price = parseFloat($tds[1].childNodes[0].nodeValue);
                 let $total = $tds[4].children[0].children[0];
                 $total.value = String(price * num);
                 cartTable.row().data()[4] = String(num * price);
                 calc_cart();
                 return false;
             });
            $(document).on('keyup keypress blur change', '.sales-input', function (e) {
                var limit = $(this).attr('max');

                if(limit) {
                    if ($(this).val() > limit) {
                        $(this).val(limit);
                    }
                }

                if ($(this).val() < 0) {
                    $(this).val(0);
                }

                if ($(this).val() < 0) {
                    $(this).val(0);
                }

                var parentTr = $(this).parents('tr');
                var id = cartTable.row(parentTr).row(':last-child').data()[7];
            });

            $('.addItem').click(function () {
                var id = $(this).attr('data-id');
                var name = $(this).attr('data-name');
                var stock = $(this).attr('data-stock');
                var price = $(this).attr('data-price');
                cartTable.row.add([
                    name,
                    price,
                    id,
                    id,
                    parseFloat(price),
                    '<button class="btn btn-sm btn-danger removeItem">Remove</button>',
                    stock,
                    id,
                ]).draw(false);

                $('#item-'+id).parents('tr').addClass('d-none')
                calc_cart();
            });
            $(document).on('click', '.removeItem', function (e) {
                var parentTr = $(this).parents('tr');
                var id = cartTable.row(parentTr).data()[7];
                cartTable.row(parentTr).remove().draw(false);
                $('#item-'+id.toString()).parents('tr').removeClass('d-none');
                calc_cart();
            });
            function calc_cart(){
                let itogo = 0;// Итоговая потребительская сумма
                let table_cart = document.getElementById('cart-table').children[1] // тело таблицы
                for (let i = 0; i < cartTable.rows().count(); i++){
                    itogo += parseFloat(table_cart.children[i].children[4].children[0].children[0].value);
                }
                document.getElementById('itogo_table').children[0].children[0].children[1].innerHTML =
                     "<h4><u>" + String(itogo) + "</u></h4>";
                //проверка активности кнопки
                var button_order = document.getElementById('make_order')
                if (cartTable.rows().count() > 0){
                     button_order.disabled=false
                 }
                 else {button_order.disabled=true}
                return false;
            }
        });
    </script>
{% endblock %}

app/templates/sales/items.html
<table id="data-table" class="table table-hover table-responsive-md" style="width:100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Stock</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td class="font-weight-bolder" id="item-{{ item.id }}">{{ item.name }}</td>
            <td>{{ item.category.name }}</td>
            <td>
                {% if item.stock %}
                {{ item.stock }}
                {% else %}
                Out of Stock
                {% endif %}
            </td>
            <td>{{ item.selling_price }}</td>
            <td>
                {% if item.stock %}
                <button class="btn btn-sm btn-primary addItem" data-id="{{ item.id }}" data-stock="{{ item.stock }}" data-name="{{ item.name }}" data-price="{{ item.selling_price }}">Add</button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

app/templates/sales/orders.html
{% extends 'base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block extra_css %}
    <style>
        span {
            cursor: pointer;
        }

        .minus, .plus {
            width: 21px;
            height: 3px;
            background: #f2f2f2;
            border-radius: 4px;
            border: 1px solid #ddd;
            display: inline-table;
            vertical-align: middle;
            text-align: center;
        }

        .sales-input {
            height: 27px;
            width: 50px;
            text-align: center;
            font-size: 15px;
            border: 1px solid #ddd;
            border-radius: 2px;
            display: inline-block;
            vertical-align: middle;
        }
        .sales-input2{
            height: 27px;
            width: 50px;
            text-align: center;
            font-size: 15px;
            border: 1px solid #ddd;
            border-radius: 2px;
            display: inline-block;
            vertical-align: middle;
        }
        .total-field{
            width: 75px;
        }

        .dataTables_filter {
           float: left !important;
        }
    </style>
{% endblock %}

{% block content %}
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <table id="cart-table" class="table table-hover table-sm" style="width:100%">
                        <thead>
                            <tr>
                                <th style="width: 900px">Товар</th>
                                <th style="width: 50px">Цена</th>
                                <th style="width: 50px">Количество</th>
                                <th style="width: 50px">Скидка</th>
                                <th style="width: 50px">Стоимость</th>
                            </tr>
                        </thead>
                    {% for order in orders %}
                        <tr>
                            <td>
                                <h4>Заказ № {{ order.id }} от {{ order.created_date|date:"d.m.Y" }}. Статус заказа {{ order.status.description }} </h4>
                            </td>
                        </tr>
                            {% for clause in order.itemtransfer_set.all %}
                                <tr>
                                    <td>{{clause.item.name}}</td><td>{{clause.item.selling_price}}</td>
                                    <td>{{clause.quantity}}</td><td>0%</td><td>{{ clause.total }}</td>
                                </tr>
                            {% endfor %}
                        <tr>
                            <td>
                                <h5><b>Итого:</b></h5>
                            </td><td></td><td></td><td></td>
                            <td>
                               <b>{{ order.total }}</b>
                            </td>
                        </tr>
                    {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}